#!/bin/bash

show_help() {
    echo "Usage: ./clines [-h] <path>"
    echo "Counts non-empty lines of C sourse files at <path>"
}

[ "$1" == "-h" ] && show_help && exit 0
[ $# -ne 1 ] && show_help && exit 1

files=$(find "$1" -name '*.c' -o -name '*.h')
[ ! "$files" ] && echo "C source files were not found" && exit 1

counter=0
for file in $files; do
    (( counter += $(grep -c -v '^$' $file) ))
done
echo "Lines (nonempty) in total:" $counter
